"""Parse and validate paper-agent output.

Structure and per-step action legality are checked with Pydantic. Quote validity
is checked deterministically against the frozen paragraph text in the workflow,
not here. A malformed response is MODEL_INVALID_OUTPUT; a response whose quotes
cannot be located is QUOTE_MISMATCH. Both are repairable once globally.
"""

import json
import re

from pydantic import BaseModel, ConfigDict, Field, ValidationError

from paper_evidence.domain.contracts import AcademicLabel

__all__ = [
    "EvidenceDraft",
    "DecisionDraft",
    "FinalAction",
    "OutputError",
    "RetrieveAction",
    "parse_decision_output",
    "parse_query_output",
]

_FENCE = re.compile(r"```(?:json)?\s*(.*?)```", re.DOTALL)


class OutputError(ValueError):
    """A structurally invalid model response."""


class _Contract(BaseModel):
    model_config = ConfigDict(extra="forbid")


class EvidenceDraft(_Contract):
    """Only the paragraph id and the verbatim quote come from the model.

    Section, source_url and paragraph_hash are filled deterministically from the
    frozen paragraph, because bibliographic and section fields may not be
    generated by the model.
    """

    paragraph_id: str
    quote: str


class DecisionDraft(_Contract):
    label: AcademicLabel
    rationale: str
    supported_parts: list[str] = Field(default_factory=list)
    scope_differences: list[str] = Field(default_factory=list)
    limitations: list[str] = Field(default_factory=list)
    evidence: list[EvidenceDraft] = Field(default_factory=list)


class RetrieveAction(_Contract):
    action: str = "retrieve"
    queries: list[str] = Field(default_factory=list)
    neighbor_paragraph_ids: list[str] = Field(default_factory=list)


class FinalAction(_Contract):
    action: str = "final"
    decision: DecisionDraft


def _extract_json(text: str) -> dict:
    candidates = _FENCE.findall(text)
    for candidate in [*candidates, text]:
        stripped = candidate.strip()
        start = stripped.find("{")
        if start == -1:
            continue
        try:
            value = json.loads(stripped[start:])
        except ValueError:
            continue
        if isinstance(value, dict):
            return value
    raise OutputError("模型输出不是 JSON 对象")


def parse_query_output(text: str) -> list[str]:
    payload = _extract_json(text)
    queries = payload.get("queries")
    if not isinstance(queries, list) or not queries:
        raise OutputError("queries 必须是非空字符串数组")
    if not all(isinstance(item, str) and item.strip() for item in queries):
        raise OutputError("queries 含空白或非字符串项")
    return [item for item in queries]


def parse_decision_output(text: str) -> RetrieveAction | FinalAction:
    payload = _extract_json(text)
    action = payload.get("action")
    try:
        if action == "retrieve":
            return RetrieveAction.model_validate({k: v for k, v in payload.items() if k != "action"})
        if action == "final":
            return FinalAction.model_validate({"decision": payload.get("decision")})
    except ValidationError as error:
        raise OutputError("动作字段不合法") from error
    raise OutputError("未知的 action")
