"""Names fixed by docs/glossary.md; these types contain no verification logic."""

from enum import StrEnum


class TaskStatus(StrEnum):
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    BLOCKED = "BLOCKED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
    INTERRUPTED = "INTERRUPTED"


class ResultLabel(StrEnum):
    SUPPORTED = "支持"
    PARTIALLY_SUPPORTED = "部分支持"
    CONTRADICTED = "相矛盾"
    INSUFFICIENT_EVIDENCE = "证据不足"
    SOURCE_UNVERIFIABLE = "无法核验来源"


class Stage(StrEnum):
    WAIT = "wait"
    SOURCE_IDENTITY = "source_identity"
    LICENSE = "license"
    FETCH = "fetch"
    QUERY_GENERATION = "query_generation"
    RETRIEVAL = "retrieval"
    DECISION = "decision"
    EVIDENCE_VALIDATION = "evidence_validation"
    OUTPUT_REPAIR = "output_repair"


class ErrorCode(StrEnum):
    DOI_INVALID = "DOI_INVALID"
    DOI_UNRESOLVABLE = "DOI_UNRESOLVABLE"
    METADATA_NOT_FOUND = "METADATA_NOT_FOUND"
    REGISTRATION_AGENCY_UNSUPPORTED = "REGISTRATION_AGENCY_UNSUPPORTED"
    SOURCE_MISMATCH = "SOURCE_MISMATCH"
    SOURCE_UNAVAILABLE = "SOURCE_UNAVAILABLE"
    LICENSE_UNKNOWN = "LICENSE_UNKNOWN"
    LICENSE_UNSUPPORTED = "LICENSE_UNSUPPORTED"
    SOURCE_LANGUAGE_UNSUPPORTED = "SOURCE_LANGUAGE_UNSUPPORTED"
    CONTENT_INCOMPLETE = "CONTENT_INCOMPLETE"
    RETRIEVAL_FAILED = "RETRIEVAL_FAILED"
    RETRIEVAL_EMPTY = "RETRIEVAL_EMPTY"
    UPSTREAM_TIMEOUT = "UPSTREAM_TIMEOUT"
    UPSTREAM_RATE_LIMITED = "UPSTREAM_RATE_LIMITED"
    UPSTREAM_AUTH_FAILED = "UPSTREAM_AUTH_FAILED"
    UPSTREAM_INVALID_REQUEST = "UPSTREAM_INVALID_REQUEST"
    UPSTREAM_UNAVAILABLE = "UPSTREAM_UNAVAILABLE"
    TASK_TIMEOUT = "TASK_TIMEOUT"
    BUDGET_EXCEEDED = "BUDGET_EXCEEDED"
    MODEL_INVALID_OUTPUT = "MODEL_INVALID_OUTPUT"
    QUOTE_MISMATCH = "QUOTE_MISMATCH"
